quarkus.http.port=8081
quarkus.swagger-ui.always-include=true

quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.devservices.enabled=false

%dev.quarkus.datasource.jdbc.url=jdbc:h2:file:./data/simulador-dev;DB_CLOSE_ON_EXIT=FALSE
%dev.quarkus.hibernate-orm.database.generation=update

%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:simulador-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
%test.quarkus.datasource.devservices.enabled=false
%test.quarkus.hibernate-orm.database.generation=drop-and-create

%prod.quarkus.datasource.jdbc.url=jdbc:h2:file:./data/simulador;DB_CLOSE_ON_EXIT=FALSE
%prod.quarkus.hibernate-orm.database.generation=update